#ifndef __H_AGGREGATE_FILES
#define __H_AGGREGATE_FILES 

void aggregate_chunks(char*** output_filenames, char**** chunks_filenames, int nchunks, int max_degree); // aggregation of pieces generated by threads in big files
  
#endif
